# Generated by Django 3.2.25 on 2024-06-15 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('photo', models.ImageField(blank=True, upload_to='Product/', verbose_name='产品图片')),
                ('description', models.TextField(verbose_name='产品描述')),
                ('productType', models.CharField(choices=[('大气污染防治设备', '大气污染防治设备'), ('物理化学处理设备', '物理化学处理设备'), ('风机', '风机')], max_length=100, verbose_name='产品类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=1, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ('-publishDate',),
            },
        ),
    ]
