//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Management.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Orders = new HashSet<Order>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int EmployeeId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int JobId { get; set; }
    
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
        public override string ToString()
        {
            return $"Employee Information:\n+ Employee ID: {EmployeeId}\n+ Last Name: {LastName}\n" +
                   $"+ First Name: {FirstName}\n+ Phone Number: {PhoneNumber}\n+ Email: {Email}\n+ Job ID: {JobId}";
        }
        public List<Employee> GetAllEmployees()
        {
            List<Employee> listE = new List<Employee>();
            using (HiTechDBEntities1 db = new HiTechDBEntities1())
            {
                var selectAll = (from e in db.Employees
                                 select e).ToList();
                Employee emp;

                foreach (var item in selectAll)
                {
                    emp = new Employee();
                    emp.EmployeeId = item.EmployeeId;
                    emp.LastName = item.LastName;
                    emp.FirstName = item.FirstName;
                    emp.PhoneNumber = item.PhoneNumber;
                    emp.Email = item.Email;
                    emp.JobId = item.JobId;

                    listE.Add(emp);
                }
            }
            return listE;
        }
    }
}
