# Generated by Django 3.2.25 on 2024-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2024-06-14', verbose_name='出生日期'),
        ),
    ]
